### PR TITLE
Lifemapper Example

### PR DESCRIPTION
**Pull request by trshaffer**
This is a cleaned up Lifemapper demo suitable for inclusion in the Makeflow examples. This version includes all the software pieces required as well as a shareable sample dataset. I removed the setup for nested workflows we used in the paper, as this introduces a fair amount of complexity and requires arranging `$PATH` or preparing precompiled `makeflow` for worker nodes. I also tried to make the dependency relationships a bit more clear. I've tested locally and with WQ+Condor following the README.

### CODE REVIEW

**Comment by trshaffer** [comment]
I almost forgot, this depends on cooperative-computing-lab/cctools#1948

**Comment by dthain** [comment]
Oh, I just noticed you have `java8_run` as a self-extracting archive.
+1 for easy self-contained reproducibility
-1 for big binaries in the archive.

Are there any legal restrictions on redistributing the JRE?
Is there a not-awful way to indicate Java 8 as a dependency but not include it?
Maybe some copy-pasta to download/install if needed?

**Comment by trshaffer** [comment]
I wasn't the one who obtained that Java runtime in the first place, so I'm not sure what restrictions are in place. I can rebase it out. Installing Java depends on the platform, so I'd be inclined to just link to the [downloads page](https://java.com/en/download/manual.jsp) in case it's not already installed.

**Comment by dthain** [comment]
Hmm, I'm just wondering if there is anything "special" about that particular java installation.

**Comment by trshaffer** [comment]
Nothing particularly special. We only included that because some of the Condor pool doesn't have Java installed. It just tested it with the Java on my workstation, no problems.

**Comment by dthain** [comment]
When I run this, I see lots of errors:

```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at density.Project.projectGrid(Project.java:152)
	at density.Project.doProject(Project.java:112)
	at density.Project.main(Project.java:522)
```

And:

```
Warning: Sample at 32.2275, -109.781389 in Conanthalictus_conanthi.csv is outside the bounding box of environmental data, skipping
Warning: Sample at 32.2275, -109.781389 in Conanthalictus_conanthi.csv is outside the bounding box of environmental data, skipping
Warning: Sample at 32.2275, -109.781389 in Conanthalictus_conanthi.csv is outside the bounding box of environmental data, skipping
Warning: Sample at 32.2275, -109.781389 in Conanthalictus_conanthi.csv is outside the bounding box of environmental data, skipping
Warning: Sample at 32.2275, -109.781389 in Conanthalictus_conanthi.csv is outside the bounding box of environmental data, skipping
```

Is that expected behavior?  if so, it should be discussed in the README.

(Is this an opportunity to use wrappers to address the problem?)

Also, the dot image isn't as interesting as the previous one, was that generated using `make_image.sh`?  Maybe use a larger example?

**Comment by trshaffer** [comment]
That's expected behavior. The failures are data dependent, so I don't think wrappers would help reducing the noise. I could look at using them for cleanup actions, though, as I currently just stuck extra bits on the ends of the commands.

I can generate an image of an expanded taxon like we used in the paper. I was just using the ones that actually run in this example.

**Comment by trshaffer** [comment]
I did a synthetically expanded taxon as in the paper. I also used `make_image.sh` and updated the banner.

**Comment by dthain** [comment]
Tim, we let this one slip, let's get it fixed up.

The Lifemapper part looks good to me know.

The only thing I notice now is that the images changed and they seem a little off -- the more dense images (hecil, bwa-gatk) are barely readable.  Did something change in the image generation that we missed?

**Comment by dthain** [comment]
I have 2.40.1 on my mac and 2.30.1 in ccl software.

Can you check if one or the other gives better results?

(It's a small thing, but very highly visible to potential users...)

**Comment by trshaffer** [comment]
I got 2.40.1 from `cclimport`, and same issue. Where were these generated originally?

**Comment by trshaffer** [comment]
It looks like the current graphic (for hecil at least) has *far* fewer nodes, so it makes sense that the newly generated ones are harder to read. Something is weird here....

**Comment by trshaffer** [comment]
So commit 9f5c771 changed hecil.mf without updating the image. The corresponding PNG hasn't been updated since a couple of months before that commit. I guess a few of the examples have gotten out of sync.

**Comment by dthain** [comment]
Aha, I see you are right.

Please see what you can do to make the images a little more pleasing, using
the workflows as they are.
Maybe it's just a matter of (not) antialiasing or downsampling or something
like that in order to visualize.

**Comment by trshaffer** [comment]
I can play with the image size, but those ones just have too many nodes to view without zooming and scrolling. When scaled down for the banner, we'd have the same problem. For the moment, I rebased the other examples out of this PR.

**Pull request merged**
